from env import *

#   app config

KEY_TOKEN_AUTH = KEY_TOKEN_AUTH_env
SECRET_KEY = SECRET_KEY_env
MYSQL_DB = MYSQL_DB_env
MYSQL_PASSWORD = MYSQL_PASSWORD_env
MYSQL_PORT = MYSQL_PORT_env
MYSQL_USER = MYSQL_USER_env
MYSQL_PORT = MYSQL_PORT_env
MYSQL_HOST = MYSQL_HOST_env

#   mailconfig

PROVEEDOR_MAIL = PROVEEDOR_MAIL_env
CORREO_MAIL = CORREO_MAIL_env
PASSWORD_MAIL = PASSWORD_MAIL_env

# # DropBox Config

# ACCESS_TOKEN = TOKEN_DROPBOX_env